### ISSUE TITLE
S905w2

### ISSUE THREAD

**Issue by Filester10** [EmuELEC/EmuELEC#1020]
Hello, I have an amlogic s905w2... gxl_p281_2g.dtb doesn't work, I can't start emuelec...
Can anyone help?
Compliments

**Comment by 7Ji** [comment]
1. Read and follow the template before opening any issue: https://github.com/EmuELEC/EmuELEC/issues/604. You did not provide any specific info about your message, the generic description helps nothing about the support. **Use template and fill-in the device info.**
2. Github issues is for actual issue about the EmuELEC (e.g. Software A breaks on condition B on device C, emulator D does not work as intendetd, etc), **not** for support advice, use our [discord server](https://discord.gg/cbgtJTu) or [forum](https://emuelec.discourse.group/) instead for that
3. Down to the issue itself, if you want us to help you sort this out, no matter you continue it on Discord on forum, make sure you give more details on it:
    > I can't start emuelec...

   Instead of this, describe where you're stuck
    > I have  an amlogic s905w2.

   Instead of this, write you device name and the spec, not just the name of the SoC
