### ISSUE TITLE
Brightness keys not mapped on GameForce Chi

### ISSUE THREAD

**Issue by gingerbeardman** [EmuELEC/EmuELEC#1137]
**Is your feature request related to a problem? Please describe.**

Brightness keys not mapped on GameForce Chi
- https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emuelec/gamepads/gameforce_gamepad.cfg

**Describe the solution you'd like**
Additional key mappings
- L3 + L1 brightness-
- L3 + R1 brightness+

**Describe alternatives you've considered**
- synced brightness, seems to be broken currently #1136 
- changing manually also has problems #1135

**Additional context**
- same query https://emuelec.discourse.group/t/oga-v1-1-emuelec-4-5-brightness/1426
- this key mapping said to exist https://github.com/EmuELEC/EmuELEC/wiki/HotKeys-for-Odroid-Go-Advance%2C-Odroid-Go-Super-and-GameForce-Chi

**Comment by Langerz82** [comment]
hmm, I believe retroarch by default does not have shortcuts for it to be changed, so this will be a feature request. We would have to make an external listener that waits for input and changes it accordingly. Most likely gptokeyb.
I can fix the other issues, but this might have to be put on hold, unless someone else decides to implement the feature.

**Comment by Langerz82** [comment]
You are right sorry, my bad.

I have an Odroid Go Advance like device so I'll see if it has the same issue.

**Comment by miwasp** [comment]
Setting brightness is mapped to GHK + left/right. GHK on GF is „1“. This works but no overlay is displayed.

What is L3?

**Comment by gingerbeardman** [comment]
Ah! On GameForce Chi the lower left rectangular face buttons are marked 1 & 2.

I incorrectly assumed GHK was the Chi home button.

I can confirm that pressing GHL "1" and left/right changes brightness in both ES and RA.

So, I consider this closed! 


thanks

**Comment by Cathodeus** [comment]
@gingerbeardman Your assumption was right the "User Manual" says that GHK button is the Home Button, And pressing it with left/right should drive the brightness. But it doesn't work !!! We have to press another button ... the "1" button ... and as it isn't what says the user manual than it is confusing !!! I really would like to be hable to drive beightness with the good button !

**Comment by Cathodeus** [comment]
This issue should be re opened. Based on my previous post explanations i guess ...

**Comment by shantigilbert** [comment]
> This issue should be re opened. Based on my previous post explanations i guess ...

No, we do not make the GameForce, and we are not responsible for the manual, we however have the hotkeys listed here: 

https://github.com/EmuELEC/EmuELEC/wiki/HotKeys-for-Odroid-Go-Advance,-Odroid-Go-Super-and-GameForce-Chi

and those are the ones that will stay.

**Comment by Cathodeus** [comment]
Hello, 
Thanks for your informations. I totally agree with those shortcuts, we're not asking to change them.

Here is a picture to clarify and maybe find a solution together :
Please have a look
[(https://www.dropbox.com/s/0rg5kwifjgra5ai/2023-03-16_11-23-45.pdf?dl=0)]

What i'm trying to understand here is : 

- Why do all these shortcuts works with the home button wich is the official GHK button from user manual, while only the brightness shortcuts doesn't ... instead of changing the screen brightness it change the save state slot.

Couple additional informations/questions :

-Why do Emuelec do not use the same button as the one in the user manual.
-Is there a way user wise to re assign the GHK button to the official one.
-Why do all shortcuts works with the official button, but the brightness screen one do not ...
