### ISSUE TITLE
Pressing Hotkey to quit game.

### ISSUE THREAD

**Issue by fayehoo** [EmuELEC/EmuELEC#282]
Now quit the game is "hotkey + start", press twice.  Can emuelec  be set to just press “hotkey” twice to quit the game？It's easier for kids.

**Comment by shantigilbert** [comment]
I think you can set it up on Retroarch, but not sure on the other emulators.

**Comment by Cee123** [comment]
I was messing around with this a bit the other day. What you can do is go into retroarch, then go into Input > Hotkeys and you can turn off "Confirm Quit" if you want to press the button once to exit a game (i personally find the double press annoying). But anyways, scroll down to the binding for "Restart Retroarch" (quit) and bind that to the same as the home key. But the problem then is because you have a hotkey set and the quit button set as the same as the home button, you cannot use the hotkey for anything else (like accessing the retroarch menu). So also change Menu Toggle Gamepad Combo to L + R together (or any other combo). Then save configuration. So it's pretty easy. You can also set the home button as exit in Drastic.

**Comment by Cee123** [comment]
![ice_screenshot_20201014-172431](https://user-images.githubusercontent.com/43462099/95970303-603a5c80-0e42-11eb-8a51-cb9a0649a1f4.png)

![ice_screenshot_20201014-172339](https://user-images.githubusercontent.com/43462099/95970319-64ff1080-0e42-11eb-9b7f-052d44ce1319.png)

![ice_screenshot_20201014-172407](https://user-images.githubusercontent.com/43462099/95970333-68929780-0e42-11eb-89b5-653d089ca2ae.png)

**Comment by shantigilbert** [comment]
@fayehoo The solution by @Cee123 is the way to do it. Thanks for sharing.

**Comment by Cee123** [comment]
@shantigilbert No worries.

**Comment by davibaltar** [comment]
Hello there. I've updated to the version 4.3 and I'm having the same problem. I've tried to configure following the @Cee123 images, but for any hotkey it doesn't work. Does anyone have an idea what it could be?
