### ISSUE TITLE
Emulation station settings not working on some emulators

### ISSUE THREAD

**Issue by blingottm** [EmuELEC/EmuELEC#336]
For example if I try to change ratio or shaders in emulation station  for sega genesis or negeo pocket color it will not change. There might be other emulators with this issue .

**Comment by shantigilbert** [comment]
Confirmed, can you go into `/emuelec/scripts/setsettings.sh` and change the line that says

`group_platform ${PLATFORM}`

and change it to 

`# group_platform ${PLATFORM}`

then it should work.

BTW this should not be considered a final fix, since I am not sure what other issues might arise from this change.

**Comment by shantigilbert** [comment]
Try latest test release: https://github.com/EmuELEC/EmuELEC-tests/releases/tag/4.0-TEST-01012021
