### ISSUE TITLE
[OGA] Minor issue - Rom name not scrolling when it is scrapped (EmuElec Carbon theme)

### ISSUE THREAD

**Issue by Erasilia** [EmuELEC/EmuELEC#340]
Hello,
First of all, thanks a lot for this OS, it's really great and I love it !

(Sorry for my shitty English)
I have a minor issue (but very visible) on the theme EmuElec Carbon (default theme). When the game is scrapped and it's too long, it doesn't scroll, only the game description does. I have not this issue on other themes and when a game is not crapped.
It seems when the game have a description, it break the name scrolling.

1. Select Default theme (EmuElec Carbon)
2. Set the game view to "Detailled"
3. Scrap a game and rename it if necessary to make it too long for the space of the rom name.

Attended feature :
The rom name is suppose to scroll anytime when it's too long.

EmuELEC : Version 3.8
Device : OGA BE

Additional context :
I don't know if it will help, but my interface is set in French.

Thanks in Advance ! :)

**Comment by shantigilbert** [comment]
Can you tell me which theme does scroll?

**Comment by dm2912** [comment]
Have done some testing. There's some sort of bug with that theme where text doesn't scroll if the text list is more than 380 wide :S

Here i have dropped the gamelist width down low to force scrolling to see if it works, and it does.. 

https://cloud.dimspace.xyz/s/8JntL3fteipeemX

Now look what happens when i make the gamelist just a bit wider, text doesn't scroll anymore.

https://cloud.dimspace.xyz/s/44KfFNjqsrsrtZ3

I have no idea why this is.. 

I tried my own theme and set the gamelist width to 450 (which is same width as that in carbon) and it still scrolls

https://cloud.dimspace.xyz/s/4spcGd34nS4Fn7B

So there's some bug in carbon whereby scrolling doesn't happen once text gamelist is > .38 wide and I cant work out why, have pored through the xml and nothing is standing out.. 

 Its possibly known and because there is such a tiny likelehood of a game title being that long that its not been addressed.

**Comment by Erasilia** [comment]
@dm2912 Thanks !

**Comment by shantigilbert** [comment]
Since this is theme related (out of EmuELEC's control) I will close this issue now, if you think it is related to EmuELEC then please reopen with the new info.
