### ISSUE TITLE
EmuELEC 4.0 on OGA: shell login shows 99-emuelec.conf: line 167: syntax error

### ISSUE THREAD

**Issue by mtoensing** [EmuELEC/EmuELEC#446]
<img width="795" alt="Screen Shot 2021-02-09 at 12 09 33" src="https://user-images.githubusercontent.com/136737/107355580-f8361300-6acf-11eb-908e-ff28b91de784.png">

A fresh install after two reboots. I can connect but get this error.

**Comment by TheLastProject** [comment]
This was fixed in 597b8729000c4d53cc036e36b015aae1a66693da.

A small update has been uploaded, that fixes the script error. You have 2 options (since its the same version) do a Force Update (Start, EmuELEC Settings, Danger Zone, Force Update) or download the .tar file corresponding to your device from the same link in #official-releases  and copy it to the .update folder either by copying it directly to the EEROMS partition/.update or using samba to the "Update" share. 

"Force Update" is easier, but will most likely need to re-setup your gamepads, everything else should stay the same.

(https://discord.com/channels/570131631260696576/570131631713550337/808794008499257415)
