### ISSUE TITLE
Wifi adapter Edimax N150 EW-7811Un V2 not working

### ISSUE THREAD

**Issue by daydaychao** [EmuELEC/EmuELEC#544]
Wifi adapter Edimax N150 EW-7811Un V2 not working

I set SSID and Password so many times but it no networks found.
Please check it out

My device: OGS
https://www.hardkernel.com/shop/odroid-go-super-dim-gray/

My Wifi adapter:
https://www.edimax.com/edimax/merchandise/merchandise_detail/data/edimax/us/wireless_adapters_n150/ew-7811un_v2/

I installed emuELEC 4.0
EmuELEC-OdroidGoAdvance.aarch64-4.0-odroidgo2.img.gz

**Comment by dm2912** [comment]
Can you find out what chip is actually in it.

Because strangely, nowhere on their site, or in any of the technical details do they say what chip is in it. 

Looking at amazon q&a seems a lot of people have issues running this dongle on linux https://www.amazon.co.uk/ask/questions/Tx1A4DYWE7NQVXN/ref=ask_dp_dpmw_al_hza and the device was not supported as of kernel 4.13

**Comment by miwasp** [comment]
There are 2 versions of this stick.
Version 1 Edimax EW-7811un USB Ids 7932:7811 has a RTL8192cu chipset and works perfectly.
Version 2 Edimax EW-7811un USB Ids 7932:b811 uses a different RealTek chipset RTL8188EU which needs a different driver that is not included.
Optically both are identical.

**Comment by daydaychao** [comment]
Thank you dm2912, miwasp.
