### ISSUE TITLE
tried everything, but I can't get emuelec to work

### ISSUE THREAD

**Issue by mook4** [EmuELEC/EmuELEC#558]
Hi!
I bought an new X96 Max Plus 4TB/23GB Amologic S905x3 tv box (Geekbuying), especially to play games with emuelec. 

Installation just works without errors, menu also works, sound works, game controller works. 
However, when I start a game (e.g. Doom, an already installed game) I get a red screen (see photo)
![IMG_2943](https://user-images.githubusercontent.com/51931039/114309047-2347dd80-9ae6-11eb-8302-1c415e1b8695.jpg)

when I put the USB stick or SD card in my Windows 10 computer, I don't get a Fat 32 (EEROMS) partition. (see picture)
![IMG_2963](https://user-images.githubusercontent.com/51931039/114309087-43779c80-9ae6-11eb-90dd-ba9fbdf9d49f.jpg)

If I do the " check Missing Bios"  in the Game Options, I get many error messages.

specifications of my box: (by aida64 and terminal emulator apps)
![IMG_2924](https://user-images.githubusercontent.com/51931039/114309166-96515400-9ae6-11eb-8ab0-ef58f7b76f97.jpg)
![IMG_2925](https://user-images.githubusercontent.com/51931039/114309168-98b3ae00-9ae6-11eb-8547-ccc17f91477d.jpg)
![IMG_2926](https://user-images.githubusercontent.com/51931039/114309171-9c473500-9ae6-11eb-834e-3b97056bed85.jpg)
![IMG_2941](https://user-images.githubusercontent.com/51931039/114309175-9e10f880-9ae6-11eb-96e8-3b9e155289c1.jpg)

I used this file:  EmuELEC-Amlogic-ng.aarch64-4.0-Generic.img.gz
I used Etcher and Rufus to burn this file to a USB or SD (tried both, same result)
I tried a couple of device trees, but this one should be it (seems to me): sm1_s905x3_4g_1gbit.dtb

hopefully somebody can help me! Greetings from the Netherlands

**Comment by shantigilbert** [comment]
Emuelec does not occluded any games, those are launchers you are responsible for adding the files required.

**Comment by mook4** [comment]
Thank you for your quick response!
 
But if I want to add Roms:
when I put the USB stick or SD card in my Windows 10 computer, I don't get a Fat 32 (EEROMS) partition. (see picture)

**Comment by mook4** [comment]
If I do the " check Missing Bios" in the Game Options, I get hundreds error messages
![Uploading image.jpg…]()

**Comment by mook4** [comment]
Like to hear from you.

**Comment by shantigilbert** [comment]
@mook4 no idea, you need to wait until the partition is created on first boot, if not then it's a bad flash most likely.

As for the bios, doesn't it seem obvious?? The option is called "missing bios" it's showing you what bios are missing.

Since this is not really a big, but user error, please use discord for this kind of things.

**Comment by mook4** [comment]
Hi,
sorry for the inconvenience
i thought the missing bios was important to emuelec. thanks to your tip that games are not included, I can now manage via the network.
SNES games works now after a lot of days trying  😀

if anyone has a tip on how to get the Fat 32 (EEROMS) partition working please let me know. I tried different SD en USB cards. Thank you

**Comment by lethal-guitar** [comment]
@mook4

> if anyone has a tip on how to get the Fat 32 (EEROMS) partition working please let me know. I tried different SD en USB cards. Thank you

You might need to go into disk management and assign a drive letter for the partition. It happens sometimes that Windows doesn't do it automatically. You should be able to find instructions via Google. If you get stuck, feel free to ask for help on Discord (you can find the link in the README/on the Wiki). But please don't ask in this GitHub issue, GitHub issues are only for bugs

**Comment by shantigilbert** [comment]
> i thought the missing bios was important to emuelec.

It is, as if an emulator needs them it won't work, but I mean the "errors" are expected if you do not have them

**Comment by AlienatedDiego** [comment]
> if anyone has a tip on how to get the Fat 32 (EEROMS) partition working please let me know. I tried different SD en USB cards. Thank you

**Comment by AlienatedDiego** [comment]
> if anyone has a tip on how to get the Fat 32 (EEROMS) partition working please let me know. I tried different SD en USB cards. 


Español
Inglés
En ocasiones ,como ya han comentado sólo debes asignar letra a la partición en el administrador de discos de windows,algunas versiones de Windows (en mi caso win7x86) no detectan particiones en dispositivos extraibles(sd,mc,usb).si estás muy interesado existen por ahí fix para que sean detectados como hdd internos .pero es más comodo usando red compartida realmente
Sometimes, as they have already commented, you only have to assign a letter to the partition in the windows disk manager, some versions of Windows (in my case win7x86) do not detect partitions on removable devices (sd, mc, usb). If you are very interested there are fixes out there so that they are detected as internal hdd. but it is more comfortable using shared network really
