### ISSUE TITLE
psx games not showing on emuelec 3.9

### ISSUE THREAD

**Issue by wookieferret** [EmuELEC/EmuELEC#768]
Hi, I'm currently running emuelec 3.9 on a s912 android box, I'm struggling to get psx games recognised by emuelec, I have games .cue and .bin on external hard drive following the correct file structure, they show on pc but the file is empty on emuelec and I can't transfer files to roms/psx folder using FileZilla any help would be much appreciated

**Comment by AlienatedDiego** [comment]
no estoy seguro a qué se refiere con que el archivo está vacío. ha consultado la wiki? https://github.com/EmuELEC/EmuELEC/wiki/ROMS-on-USB-media

si no puede ver sus juegos compruebe que la configuración de la GUI en emuelec tiene activada la opción "mostrar carpetas". Si esto no lo resuelve, verifique si las extensiones y rutas son correctas.

Dado que 3.9 es una versión antigua sin posibilidad de cambios y no es un error del sistema en el futuro, use la discordia o el foro emuelec para estas preguntas.
I'm not sure what you mean by the file being empty. Have you consulted the wiki?

if you can't see your games check that the GUI settings in emuelec have the "show folders" option enabled. If this doesn't solve it, check if the extensions and routes are correct.

Since 3.9 is an old version with no possibility of changes and it is not a system error in the future, please use the discord or the emuelec forum for these questions.
